"""Manim 静态名称回退表 — 供未安装 Manim 的环境（如 CI）使用。

manim_validator 的 undefined-name / unknown-scene-method 检查优先使用
动态内省（dir(manim) / dir(manim.Scene)），本模块只在 import manim
失败时作为静态回退，保证无渲染依赖的环境（requirements-ci.txt 不装
manim）中检查逻辑仍可运行、行为与本地一致。

生成来源: manim 0.20.1 的公开名。
重新生成方式:

    import manim
    names = sorted(n for n in dir(manim) if not n.startswith("_"))
    attrs = sorted(n for n in dir(manim.Scene) if not n.startswith("_"))
    # 用结果替换下方两个 frozenset
"""

MANIM_PUBLIC_NAMES: frozenset[str] = frozenset({
    "AS2700", "Add", "AddTextLetterByLetter", "AddTextWordByWord", "Angle",
    "AnimatedBoundary", "Animation", "AnimationGroup", "AnnotationDot",
    "AnnularSector", "Annulus", "ApplyComplexFunction", "ApplyFunction", "ApplyMatrix",
    "ApplyMethod", "ApplyPointwiseFunction", "ApplyPointwiseFunctionToCenter",
    "ApplyWave", "Arc", "ArcBetweenPoints", "ArcBrace", "ArcPolygon",
    "ArcPolygonFromArcs", "Arrow", "Arrow3D", "ArrowCircleFilledTip", "ArrowCircleTip",
    "ArrowSquareFilledTip", "ArrowSquareTip", "ArrowTip", "ArrowTriangleFilledTip",
    "ArrowTriangleTip", "ArrowVectorField", "Axes", "BLACK", "BLUE", "BLUE_A",
    "BLUE_B", "BLUE_C", "BLUE_D", "BLUE_E", "BOLD", "BOOK", "BS381",
    "BackgroundColoredVMobjectDisplayer", "BackgroundRectangle", "BarChart", "Blink",
    "Brace", "BraceBetweenPoints", "BraceLabel", "BraceText", "Broadcast",
    "BulletedList", "CHOOSE_NUMBER_MESSAGE", "CONTEXT_SETTINGS", "CTRL_VALUE",
    "CairoRenderer", "Camera", "CapStyleType", "ChangeDecimalToValue", "ChangeSpeed",
    "ChangingDecimal", "Circle", "Circumscribe", "ClockwiseTransform", "Code",
    "ComplexHomotopy", "ComplexPlane", "ComplexValueTracker", "Cone", "ConvexHull",
    "ConvexHull3D", "CoordinateSystem", "CounterclockwiseTransform", "Create", "Cross",
    "Cube", "CubicBezier", "CurvedArrow", "CurvedDoubleArrow", "CurvesAsSubmobjects",
    "Cutout", "CyclicReplace", "Cylinder", "DARKER_GRAY", "DARKER_GREY", "DARK_BLUE",
    "DARK_BROWN", "DARK_GRAY", "DARK_GREY", "DEFAULT_ARROW_TIP_LENGTH",
    "DEFAULT_DASH_LENGTH", "DEFAULT_DOT_RADIUS", "DEFAULT_FONT_SIZE",
    "DEFAULT_MOBJECT_TO_EDGE_BUFFER", "DEFAULT_MOBJECT_TO_MOBJECT_BUFFER",
    "DEFAULT_POINTWISE_FUNCTION_RUN_TIME", "DEFAULT_POINT_DENSITY_1D",
    "DEFAULT_POINT_DENSITY_2D", "DEFAULT_QUALITY", "DEFAULT_SMALL_DOT_RADIUS",
    "DEFAULT_STROKE_WIDTH", "DEFAULT_WAIT_TIME", "DEGREES", "DL", "DOWN", "DR",
    "DVIPSNAMES", "DashedLine", "DashedVMobject", "DecimalMatrix", "DecimalNumber",
    "DecimalTable", "DefaultSectionType", "DiGraph", "DictAsObject", "Difference",
    "Dodecahedron", "Dot", "Dot3D", "DotCloud", "DoubleArrow", "DrawBorderThenFill",
    "EPILOG", "Elbow", "Ellipse", "Exclusion", "FadeIn", "FadeOut", "FadeToColor",
    "FadeTransform", "FadeTransformPieces", "Flash", "FocusOn", "FullScreenRectangle",
    "FunctionGraph", "GOLD", "GOLD_A", "GOLD_B", "GOLD_C", "GOLD_D", "GOLD_E", "GRAY",
    "GRAY_A", "GRAY_B", "GRAY_BROWN", "GRAY_C", "GRAY_D", "GRAY_E", "GREEN", "GREEN_A",
    "GREEN_B", "GREEN_C", "GREEN_D", "GREEN_E", "GREY", "GREY_A", "GREY_B",
    "GREY_BROWN", "GREY_C", "GREY_D", "GREY_E", "Graph", "Group", "GrowArrow",
    "GrowFromCenter", "GrowFromEdge", "GrowFromPoint", "HEAVY", "HSV", "Homotopy",
    "IN", "INVALID_NUMBER_MESSAGE", "ITALIC", "Icosahedron", "ImageMobject",
    "ImageMobjectFromCamera", "ImplicitFunction", "Indicate", "Integer",
    "IntegerMatrix", "IntegerTable", "Intersection", "LARGE_BUFF", "LEFT", "LIGHT",
    "LIGHTER_GRAY", "LIGHTER_GREY", "LIGHT_BROWN", "LIGHT_GRAY", "LIGHT_GREY",
    "LIGHT_PINK", "LOGO_BLACK", "LOGO_BLUE", "LOGO_GREEN", "LOGO_RED", "LOGO_WHITE",
    "Label", "LabeledArrow", "LabeledDot", "LabeledLine", "LabeledPolygram",
    "LaggedStart", "LaggedStartMap", "Line", "Line3D", "LineJointType", "LinearBase",
    "LinearTransformationScene", "LogBase", "MAROON", "MAROON_A", "MAROON_B",
    "MAROON_C", "MAROON_D", "MAROON_E", "MEDIUM", "MED_LARGE_BUFF", "MED_SMALL_BUFF",
    "MaintainPositionRelativeTo", "ManimBanner", "ManimColor", "ManimColorDType",
    "MappingCamera", "MarkupText", "MathTable", "MathTex", "Matrix", "Mobject",
    "Mobject1D", "Mobject2D", "MobjectMatrix", "MobjectTable", "MoveAlongPath",
    "MoveToTarget", "MovingCamera", "MovingCameraScene", "MultiCamera", "NORMAL",
    "NO_SCENE_MESSAGE", "NumberLine", "NumberPlane", "OBLIQUE", "ORANGE", "ORIGIN",
    "OUT", "Octahedron", "OldMultiCamera", "OpenGLPGroup", "OpenGLPMPoint",
    "OpenGLPMobject", "PGroup", "PI", "PINK", "PMobject", "PURE_BLUE", "PURE_CYAN",
    "PURE_GREEN", "PURE_MAGENTA", "PURE_RED", "PURE_YELLOW", "PURPLE", "PURPLE_A",
    "PURPLE_B", "PURPLE_C", "PURPLE_D", "PURPLE_E", "PackageNotFoundError",
    "Paragraph", "ParametricFunction", "ParsableManimColor", "PhaseFlow", "Point",
    "PointCloudDot", "PolarPlane", "Polygon", "Polygram", "Polyhedron", "Prism",
    "QUALITIES", "R3_to_complex", "RED", "RED_A", "RED_B", "RED_C", "RED_D", "RED_E",
    "RESAMPLING_ALGORITHMS", "RGBA", "RIGHT", "RandomColorGenerator", "Rectangle",
    "RegularPolygon", "RegularPolygram", "RemoveTextLetterByLetter", "RendererType",
    "ReplacementTransform", "Restore", "RightAngle", "Rotate", "Rotating",
    "RoundedRectangle", "SCALE_FACTOR_PER_FONT_POINT", "SCENE_NOT_FOUND_MESSAGE",
    "SEMIBOLD", "SEMILIGHT", "SHIFT_VALUE", "SMALL_BUFF", "START_X", "START_Y",
    "SVGMobject", "SVGNAMES", "SampleSpace", "ScaleInPlace", "Scene",
    "SceneFileWriter", "ScreenRectangle", "Section", "Sector", "ShowIncreasingSubsets",
    "ShowPartial", "ShowPassingFlash", "ShowPassingFlashWithThinningStrokeWidth",
    "ShowSubmobjectsOneByOne", "ShrinkToCenter", "SingleStringMathTex",
    "SmoothedVectorizedHomotopy", "SpecialThreeDScene", "Sphere", "SpinInFromNothing",
    "SpiralIn", "SplitScreenCamera", "Square", "Star", "StealthTip", "StreamLines",
    "Succession", "Surface", "SurroundingRectangle", "Swap", "TAU", "TEAL", "TEAL_A",
    "TEAL_B", "TEAL_C", "TEAL_D", "TEAL_E", "THIN", "Table", "TangentLine",
    "TangentialArc", "Tetrahedron", "Tex", "TexFontTemplates", "TexTemplate",
    "TexTemplateLibrary", "Text", "ThreeDAxes", "ThreeDCamera", "ThreeDScene",
    "ThreeDVMobject", "TipableVMobject", "Title", "Torus", "TracedPath", "Transform",
    "TransformAnimations", "TransformFromCopy", "TransformMatchingShapes",
    "TransformMatchingTex", "Triangle", "TrueDot", "TypeWithCursor", "UL", "ULTRABOLD",
    "ULTRAHEAVY", "ULTRALIGHT", "UP", "UR", "Uncreate", "Underline", "Union",
    "UnitInterval", "UntypeWithCursor", "Unwrite", "UpdateFromAlphaFunc",
    "UpdateFromFunc", "VDict", "VGroup", "VMobject", "VMobjectFromSVGPath",
    "ValueTracker", "Variable", "Vector", "VectorField", "VectorScene",
    "VectorizedPoint", "WHITE", "Wait", "Wiggle", "Write", "X11", "XKCD", "X_AXIS",
    "YELLOW", "YELLOW_A", "YELLOW_B", "YELLOW_C", "YELLOW_D", "YELLOW_E", "Y_AXIS",
    "Z_AXIS", "ZoomedScene", "add_extension_if_not_present", "adjacent_n_tuples",
    "adjacent_pairs", "all_elements_are_instances", "always", "always_redraw",
    "always_rotate", "always_shift", "angle_axis_from_quaternion",
    "angle_between_vectors", "angle_of_vector", "animation", "annotations",
    "assert_is_mobject_method", "average_color", "bezier", "bezier_remap",
    "binary_search", "camera", "capture", "cartesian_to_spherical", "center_of_mass",
    "change_to_rgba_array", "choose", "cli_ctx_settings", "clip", "clockwise_path",
    "color", "color_gradient", "color_to_int_rgb", "color_to_int_rgba", "color_to_rgb",
    "color_to_rgba", "compass_directions", "complex_func_to_R3_func", "complex_to_R3",
    "concatenate_lists", "config", "console", "constants", "core",
    "counterclockwise_path", "cross2d", "cycle_animation", "data_structures",
    "double_smooth", "drag_pixels", "earclip_triangulation", "ensure_executable",
    "error_console", "exponential_decay", "f_always", "find_intersection", "frame",
    "get_3d_vmob_end_corner", "get_3d_vmob_end_corner_index",
    "get_3d_vmob_end_corner_unit_normal", "get_3d_vmob_gradient_start_and_end_points",
    "get_3d_vmob_start_corner", "get_3d_vmob_start_corner_index",
    "get_3d_vmob_start_corner_unit_normal", "get_3d_vmob_unit_normal", "get_det_text",
    "get_dir_layout", "get_full_raster_image_path", "get_full_sound_file_path",
    "get_plugins", "get_shaded_rgb", "get_smooth_cubic_bezier_handle_points",
    "get_unit_normal", "get_video_metadata", "get_winding_number",
    "guarantee_empty_existence", "guarantee_existence", "hex_to_rgb", "index_labels",
    "integer_interpolate", "interpolate", "interpolate_color", "inverse_interpolate",
    "invert_color", "invert_image", "is_closed", "is_gif_format", "is_mov_format",
    "is_mp4_format", "is_png_format", "is_webm_format", "line_intersection", "linear",
    "lingering", "list_difference_update", "list_plugins", "list_update", "listify",
    "logger", "make_even", "make_even_by_cycling", "manim_colors", "match_interpolate",
    "matrix_to_mobject", "matrix_to_tex_string", "merge_dicts_recursively", "mid",
    "midpoint", "mobject", "modify_atime", "normalize", "not_quite_there", "np",
    "open_file", "opengl", "override_animate", "override_animation",
    "partial_bezier_points", "path_along_arc", "perpendicular_bisector", "plugins",
    "point_lies_on_bezier", "print_family", "proportions_along_bezier_curve_for_point",
    "quaternion_conjugate", "quaternion_from_angle_axis", "quaternion_mult",
    "random_bright_color", "random_color", "rate_functions", "register_font",
    "regular_vertices", "remove_list_redundancies", "remove_nones", "renderer",
    "rgb_to_color", "rgb_to_hex", "rgba_to_color", "rotate_vector", "rotation_about_z",
    "rotation_matrix", "running_start", "rush_from", "rush_into", "scene",
    "seek_full_path_from_defaults", "shoelace", "shoelace_direction", "sigmoid",
    "slow_into", "smooth", "smoothererstep", "smootherstep", "smoothstep",
    "spherical_to_cartesian", "split_bezier", "squish_rate_func", "straight_path",
    "stretch_array_to_length", "subdivide_bezier", "tempconfig", "there_and_back",
    "there_and_back_with_pause", "thick_diagonal", "tuplify",
    "turn_animation_into_updater", "typing", "unit", "update_dict_recursively",
    "utils", "version", "wiggle", "write_to_movie", "z_to_vector",
})

SCENE_PUBLIC_ATTRS: frozenset[str] = frozenset({
    "add", "add_foreground_mobject", "add_foreground_mobjects",
    "add_mobjects_from_animations", "add_sound", "add_subcaption", "add_updater",
    "begin_animations", "bring_to_back", "bring_to_front", "camera",
    "check_interactive_embed_is_valid", "clear", "compile_animation_data",
    "compile_animations", "construct", "embed", "get_attrs",
    "get_mobject_family_members", "get_moving_and_static_mobjects",
    "get_moving_mobjects", "get_restructured_mobject_list", "get_run_time",
    "get_time_progression", "get_top_level_mobjects", "interact", "interactive_embed",
    "is_current_animation_frozen_frame", "mouse_drag_orbit_controls",
    "mouse_scroll_orbit_controls", "next_section", "on_key_press", "on_key_release",
    "on_mouse_drag", "on_mouse_motion", "on_mouse_press", "on_mouse_scroll", "pause",
    "play", "play_internal", "remove", "remove_foreground_mobject",
    "remove_foreground_mobjects", "remove_updater", "render", "replace",
    "restructure_mobjects", "set_key_function", "setup", "should_update_mobjects",
    "tear_down", "time", "update_meshes", "update_mobjects", "update_self",
    "update_to_time", "validate_run_time", "wait", "wait_until",
})
